wp:
    image: mod-wp
    links:
        - mysql:mysql
    ports:
        - "80"
    volumes_from:
        - paasdata

mysql:
    image: mysql
    volumes_from:
        - paasdata
    environment:
        - MYSQL_ROOT_PASSWORD=myrootpass

paasdata:
    image: oskarhane/data
    # build: [path]
    command: tail -f /dev/null