webserver:
  image: wordpress
  ports:
    - "80:80"
  links:
    - "dbserver:mysql"

dbserver:
  image: mysql
  volumes_from:
    - dataonly
  environment:
    MYSQL_ROOT_PASSWORD: password

dataonly:
  build: /Users/yunseopkim/oneday_onecommit/docker_study/wp-example/dataonly
  volumes:
    - /Users/yunseopkim/oneday_onecommit/docker_study/wp-example/data:/var/lib/mysql
  command: tail -f /dev/null